version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "functions/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd functions && yarn install

      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-{{ checksum "functions/package.json" }}

      - run: cd functions && yarn lint
      - run: cd functions && yarn test
      - run: ./functions/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -P development
      - run: ./functions/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -P production
